# Generated by Django 5.2.13 on 2026-05-05 05:48

import course.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Centre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("centre_name", models.CharField(max_length=200)),
                ("centre_address", models.TextField()),
                ("centre_contact", models.CharField(max_length=15)),
                ("centre_email", models.EmailField(max_length=254)),
                ("centre_desc", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_name", models.CharField(max_length=200)),
                ("course_desc", models.TextField()),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("course_duration", models.CharField(max_length=100)),
                (
                    "course_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("ongoing", "Ongoing"),
                            ("open", "Open for Registration"),
                            ("closed", "Registration Closed"),
                            ("completed", "Completed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "course_fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Course Fees",
                    ),
                ),
                ("is_free", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Course Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Course End Date"
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Registration Deadline"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=course.models.course_image_upload_path,
                        verbose_name="Course Image",
                    ),
                ),
                (
                    "syllabus_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=course.models.course_syllabus_upload_path,
                        verbose_name="Syllabus/Module Document (PDF)",
                    ),
                ),
                (
                    "modules_info",
                    models.TextField(
                        blank=True,
                        help_text="Enter module details, topics covered, syllabus structure",
                        null=True,
                        verbose_name="Course Modules/Syllabus Info",
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True, null=True, verbose_name="Prerequisites"
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Learning Outcomes"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="offline",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "max_seats",
                    models.PositiveIntegerField(
                        blank=True, default=30, null=True, verbose_name="Maximum Seats"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
