# Generated by Django 5.2.13 on 2026-05-05 06:22

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centre",
            options={"ordering": ["centre_name"]},
        ),
        migrations.AlterField(
            model_name="course",
            name="course_duration",
            field=models.CharField(help_text="e.g., 3 months, 6 weeks", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_fees",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=course.models.course_image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="learning_outcomes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="max_seats",
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="modules_info",
            field=models.TextField(
                blank=True,
                help_text="Enter module details, topics covered, syllabus structure",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="prerequisites",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="registration_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="syllabus_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=course.models.course_syllabus_upload_path,
            ),
        ),
    ]
