# Generated by Django 5.2.13 on 2026-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_centre_options_alter_course_course_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="available_centres",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select centres where this course is offered",
                related_name="available_courses",
                to="course.centre",
            ),
        ),
    ]
