# Generated by Django 5.2.13 on 2026-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_course_available_centres"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Course (Multiple Days/Weeks)"),
                    ("workshop", "Single Day Workshop/Event"),
                    ("seminar", "Seminar"),
                    ("webinar", "Webinar"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="event_date",
            field=models.DateField(
                blank=True, help_text="For single day events/workshops", null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_duration",
            field=models.CharField(
                blank=True,
                help_text="e.g., 3 months, 6 weeks (for regular courses)",
                max_length=100,
                null=True,
            ),
        ),
    ]
