# Generated by Django 5.2.13 on 2026-05-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_course_course_type_course_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Course (Multiple Days/Weeks)"),
                    ("workshop", "Single Day Workshop/Event"),
                    ("Online Bootcamp", "Online Bootcamp"),
                    ("seminar", "Seminar"),
                    ("webinar", "Webinar"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
    ]
