# Generated by Django 5.2.13 on 2026-05-04 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("mobile_number", models.CharField(max_length=10, unique=True)),
                ("date_of_birth", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("sc", "SC"),
                            ("st", "ST"),
                            ("ews", "EWS"),
                            ("obc", "OBC"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                ("father_name", models.CharField(max_length=200)),
                ("is_approved", models.BooleanField(default=False)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_enrolled",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="course.course",
                    ),
                ),
                (
                    "preferred_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="course.centre",
                    ),
                ),
            ],
            options={
                "ordering": ["-registration_date"],
            },
        ),
    ]
