# Generated by Django 5.2.13 on 2026-05-05 05:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", "Enter a valid 10-digit mobile number"
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("sc", "SC"),
                            ("st", "ST"),
                            ("ews", "EWS"),
                            ("obc", "OBC"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                ("father_name", models.CharField(max_length=200)),
                ("is_approved", models.BooleanField(default=False)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_enrolled",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="course.course",
                    ),
                ),
                (
                    "preferred_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="course.centre",
                    ),
                ),
            ],
            options={
                "ordering": ["-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                (
                    "certificate_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="registration.student",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["email_id", "course_enrolled"],
                name="registratio_email_i_10e534_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["mobile_number", "course_enrolled"],
                name="registratio_mobile__2a2ad3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["registration_number"], name="registratio_registr_720d13_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("email_id", "course_enrolled")},
        ),
    ]
