# Generated by Django 5.2.13 on 2026-05-10 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_course_course_type"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="preferred_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="course.centre",
            ),
        ),
    ]
